#!/bin/sh

[ "${ACTION}" = "ifup" ] || exit 0
[ "$(uci -q get maccloner.settings.enabled)" = "1" ] || exit 0

. /lib/functions/network.sh

DEVICE_NAME="${DEVICE:-$INTERFACE}"

logger -t maccloner "Hotplug triggered for $INTERFACE (device: $DEVICE_NAME)"

idx=0
while true; do
    rule_section="maccloner.@rule[${idx}]"
    uci -q get ${rule_section}.interface >/dev/null || break
    idx=$((idx + 1))

    [ "$(uci -q get ${rule_section}.enabled)" = "1" ] || continue

    RULE_IFACE=$(uci -q get ${rule_section}.interface)
    TARGET_SSID=$(uci -q get ${rule_section}.target_ssid)
    CUSTOM_MAC=$(uci -q get ${rule_section}.custom_mac)

    if [ "$DEVICE_NAME" != "$RULE_IFACE" ] && [ "$INTERFACE" != "$RULE_IFACE" ]; then
        continue
    fi

    [ -z "$CUSTOM_MAC" ] && continue

    if iwinfo "$RULE_IFACE" info >/dev/null 2>&1; then
        CURRENT_SSID=$(iwinfo "$RULE_IFACE" info | sed -n 's/.*SSID: "\(.*\)"/\1/p')
        if [ -n "$TARGET_SSID" ] && [ "$CURRENT_SSID" != "$TARGET_SSID" ]; then
            logger -t maccloner "SSID mismatch ($CURRENT_SSID != $TARGET_SSID), skipping."
            continue
        fi
    fi

    CURRENT_MAC=$(cat /sys/class/net/$RULE_IFACE/address 2>/dev/null | tr '[:upper:]' '[:lower:]')
    if [ "$CURRENT_MAC" = "$(echo $CUSTOM_MAC | tr '[:upper:]' '[:lower:]')" ]; then
        exit 0
    fi

    logger -t maccloner "Changing MAC of $RULE_IFACE to $CUSTOM_MAC (SSID: ${TARGET_SSID:-any})"

    ip link set dev "$RULE_IFACE" down
    ip link set dev "$RULE_IFACE" address "$CUSTOM_MAC"
    ip link set dev "$RULE_IFACE" up

    logger -t maccloner "MAC changed. wpa_supplicant will reassociate automatically."
    break
done
